"""PatientHealthRecord table

Revision ID: 00110b6d36ba
Revises: 479ebee6c82e
Create Date: 2018-04-25 12:36:32.846897

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00110b6d36ba'
down_revision = '479ebee6c82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patint_health_record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.String(length=80), nullable=True),
    sa.Column('allergym', sa.String(length=255), nullable=True),
    sa.Column('bpsys', sa.Integer(), nullable=True),
    sa.Column('bpdia', sa.Integer(), nullable=True),
    sa.Column('heartbeat', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('weight', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('patint_health_record')
    # ### end Alembic commands ###
