"""users table

Revision ID: 0117bee9ba29
Revises: 
Create Date: 2018-04-10 22:25:11.264307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0117bee9ba29'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('dayavail', sa.String(length=128), nullable=True))
    op.add_column('user', sa.Column('endtime', sa.String(length=80), nullable=True))
    op.add_column('user', sa.Column('starttime', sa.String(length=80), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'starttime')
    op.drop_column('user', 'endtime')
    op.drop_column('user', 'dayavail')
    # ### end Alembic commands ###
