"""User table

Revision ID: 05414dce65c9
Revises: 479ebee6c82e
Create Date: 2018-04-23 17:09:55.273013

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '05414dce65c9'
down_revision = '479ebee6c82e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('day_avail_s', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'day_avail_s')
    # ### end Alembic commands ###
