"""users table

Revision ID: 43db25fba480
Revises: 45c48796a531
Create Date: 2018-04-13 18:42:05.020168

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43db25fba480'
down_revision = '45c48796a531'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=140), nullable=True),
    sa.Column('slot', sa.String(length=140), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('doctor_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['doctor_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_appointments_timestamp'), 'appointments', ['timestamp'], unique=False)
    op.add_column('user', sa.Column('email', sa.String(length=128), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email')
    op.drop_index(op.f('ix_appointments_timestamp'), table_name='appointments')
    op.drop_table('appointments')
    # ### end Alembic commands ###
