"""User table

Revision ID: 479ebee6c82e
Revises: 84bf4773c758
Create Date: 2018-04-17 14:53:37.815734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '479ebee6c82e'
down_revision = '84bf4773c758'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bank_info',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('bankname', sa.String(length=80), nullable=True),
    sa.Column('ifsc', sa.String(length=80), nullable=True),
    sa.Column('acctname', sa.String(length=80), nullable=True),
    sa.Column('acctnum', sa.String(length=128), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reimbdata',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('brno', sa.String(length=80), nullable=True),
    sa.Column('date', sa.String(length=80), nullable=True),
    sa.Column('amount', sa.String(length=128), nullable=True),
    sa.Column('status', sa.String(length=80), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reimbdata')
    op.drop_table('bank_info')
    # ### end Alembic commands ###
