"""users table

Revision ID: 45c48796a531
Revises: 0117bee9ba29
Create Date: 2018-04-10 22:41:24.622977

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '45c48796a531'
down_revision = '0117bee9ba29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('hospital', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'hospital')
    # ### end Alembic commands ###
